version: 3.1.{build}
configuration:
  - Release
image: Visual Studio 2022
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  - nuget restore src\Serialize.Linq.sln
build:
  project: src\Serialize.Linq.sln
artifacts:  
  - path: '**\*.nupkg'
deploy:
  provider: NuGet
  on:
    branch: main
  api_key:
    secure: vJ/dCjDaMcX6hUlmQBlz5fDgxo/oFr9BsUhHy/6LUXQNjp3LIv3n4lMwQuiyOjDD
  skip_symbols: false
  artifact: /.*(\.|\.s)nupkg/